"""update nos status pendente

Revision ID: 2e741c40e938
Revises: 55292c0e40b1
Create Date: 2025-01-03 10:11:22.227910

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e741c40e938'
down_revision: Union[str, None] = '55292c0e40b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activitys', 'status',
               existing_type=postgresql.ENUM('PENDING', 'TODO', 'INPROGRESS', 'DONE', name='new_todostate'),
               type_=sa.Enum('PENDING', 'TODO', 'INPROGRESS', 'WAITING', 'DONE', name='todostate'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activitys', 'status',
               existing_type=sa.Enum('PENDING', 'TODO', 'INPROGRESS', 'WAITING', 'DONE', name='todostate'),
               type_=postgresql.ENUM('PENDING', 'TODO', 'INPROGRESS', 'DONE', name='new_todostate'),
               existing_nullable=False)
    # ### end Alembic commands ###
