"""create table project

Revision ID: 5a50d9356b9d
Revises: 4f71dd4f5aab
Create Date: 2024-12-17 11:19:55.309706

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a50d9356b9d'
down_revision: Union[str, None] = '4f71dd4f5aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_project', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activitys', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint('activitys_customer_id_fkey', 'activitys', type_='foreignkey')
    op.create_foreign_key(None, 'activitys', 'projects', ['project_id'], ['id'])
    op.drop_column('activitys', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitys', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activitys', type_='foreignkey')
    op.create_foreign_key('activitys_customer_id_fkey', 'activitys', 'users', ['customer_id'], ['id'])
    op.drop_column('activitys', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
