"""Initial migrations

Revision ID: 758e00cf8b64
Revises: 
Create Date: 2025-01-03 09:18:31.504073

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '758e00cf8b64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
