"""Delete em cascata

Revision ID: 933afc408d04
Revises: aa8fd2655a6a
Create Date: 2024-12-23 11:54:47.039991

"""
from typing import Sequence, Union
import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '933afc408d04'
down_revision: Union[str, None] = 'aa8fd2655a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
