"""Recriação do todo

Revision ID: aa8fd2655a6a
Revises: 5a50d9356b9d
Create Date: 2024-12-20 09:31:16.769521

"""
from typing import Sequence, Union
import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'aa8fd2655a6a'
down_revision: Union[str, None] = '5a50d9356b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
