"""deletando a coluna description na table todos

Revision ID: be7ee79b5bcc
Revises: 933afc408d04
Create Date: 2025-01-02 09:17:42.026839

"""
from typing import Sequence, Union
import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'be7ee79b5bcc'
down_revision: Union[str, None] = '933afc408d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'description_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('description_activity', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
